### PR TITLE
Abs/create event

### PR DESCRIPTION
**Pull request by Deenknight**
Completed the Image functionality and added input validation to event creation

### CODE REVIEW

**Comment by antoszko** [comment]
Screenshot from 2024-12-01 17-22-38

This input breaks it

` java.lang.IllegalArgumentException: Timestamp seconds out of range: 797383058310000`

**Comment by antoszko** [comment]
Additionally, the eventDate lets you type letters but the lottery date only lets you type numbers. I think both should be limited to numebrs only

**Comment by antoszko** [comment]
Other than that it looks good, but might as well just keep going on this branch and implement event images for the event card in event list and in myEventList. As well as in OrganizerViewEvent and ViewEvent.

**Comment by Deenknight** [comment]
> Screenshot from 2024-12-01 17-22-38
> 
> This input breaks it
> 
> ` java.lang.IllegalArgumentException: Timestamp seconds out of range: 797383058310000`

fixed

**Comment by Deenknight** [comment]
> Additionally, the eventDate lets you type letters but the lottery date only lets you type numbers. I think both should be limited to numebrs only

fixed

**Comment by Deenknight** [comment]
> Other than that it looks good, but might as well just keep going on this branch and implement event images for the event card in event list and in myEventList. As well as in OrganizerViewEvent and ViewEvent.

this is not how branches work but yes i'll keep working on it

**Pull request merged**
