### PR TITLE
Db client completed

### PR DESCRIPTION
**Pull request by Deenknight**
Created the db client class, with some implementation shown with the CreateEventFragment.

### CODE REVIEW

**Review by Sherali5543 — APPROVED** [review]
LGTM!

**Comment by antoszko** [comment]
whats the purpose of the wrapping the db.write data with a db.count()?

**Review by antoszko — APPROVED** [review]
DB works though. so other than my previous question looks good

**Comment by Deenknight** [comment]
@antoszko All firestore operations are asynchronous, so writeData is in the onSuccess method of count so it can only be called once count completes.

**Pull request merged**
